apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-backstage
  description: This is my first Backstage service!
  tags:
    - demo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
